spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  security:
    user:
      name: lukasz
      password: lukasz
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:h2:mem:test
    username: lukasz
    password: lukasz
  h2:
    console:
      enabled: true

#logging:
#  level:
#    root: debug

server:
  error:
    whitelabel:
      enabled: false
    path: /error





